dir = "/var/lib/immudb"
network = "tcp"
address = "0.0.0.0"
port = 3322
pidfile = "/var/lib/immudb/immudb.pid"
logfile = "/var/log/immudb/immudb.log"
mtls = false
auth = true
pgsql-server = true
pgsql-server-port = 5432
devmode = false
maxActiveSnapshots = 1200
