# https://taskfile.dev

version: '3'

tasks:
  update:
    desc: Update the shasums of the package contents
    cmds:
      - updpkgsums
  build:
    desc: build the package
    cmds:
      - makepkg
      - makepkg --printsrcinfo > .SRCINFO
  clean:
    desc: Clean up build folders.
    cmds:
      - rm -rf ./src ./pkg
      - rm -f *.log*
      - rm -f *.zst
      - rm -rf data
      - rm -f immudb.service
